[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "b7e80dca7855b811ad8c8bf5c2a7d242faf4e5e6"
os = "macos"

    [[GAP_pkg_anupq.download]]
    sha256 = "5505cd5797c8433c373cdecdab135b6b6e7ba2beb4a90dbabb0a4927165d341e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "e391399ff79c8d80e8f036a945035f713985a68a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "8e75616eeb9807125523c73e1f54252eb80b32f2686e4c5f492f1cb4f866f1aa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "85065da51accc45a6c64947200a032287b471b58"
libc = "musl"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "fc4cabfec78aa6856a1f3f5ffb7403d6d7aaa45fc181346c70069d3dcdf7b10a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_anupq]]
arch = "powerpc64le"
git-tree-sha1 = "b04266340fe3f17e9ee06f3b7cf143992433a8d1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "d02f32fa22af155f05bd28917a20ee82b930f01ce7cff285a26917857524553b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "8301b3af6f794a7d64f07e05b2483cf0a7636f71"
os = "macos"

    [[GAP_pkg_anupq.download]]
    sha256 = "b87d4bed60d930bf18bc67bbad2153caa7c7cdf3627c6822cf99173ff2ed215d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "60fb2a72fcdf455ddfceb3de6717a1bc2756ac50"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "6ec52d5b32f38f1ffb0eab767d01ffdf78b6f1fdb250fc9bf131e43f007104b4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "8a85e0f13877f9b7225a7c5dbc9062ffd48ecc53"
libc = "musl"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "c3941d7d8d7d2313f2ef6d7cf6e1c980188d92057ac8053c42e8e8429728903d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "38f1911f4ce0f9d1eb75beb92db6598277de0b7d"
os = "freebsd"

    [[GAP_pkg_anupq.download]]
    sha256 = "af14ede4d4046b481a6f1cf2821aaf8c7de1656049ceed9eb593c1f58b82a0a0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.0+0/GAP_pkg_anupq.v300.300.0.x86_64-unknown-freebsd.tar.gz"
