[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "f222aaded22304c47dc1fe7ef7d2e5d6da1eb95f"
os = "macos"

    [[GAP_pkg_anupq.download]]
    sha256 = "9a152b6f95972bc42226439e2b8f9d34f5fd5196e081cfc0e5b1efa1aba4de19"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "b6fed955968f11726dc2e659a9c3a2bc2ca9f861"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "58943d1b88edfe17461e4e07a267c79402e017cffe81b498a9f1fe6cfa4d4541"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "350d20688dfeeb94847381a14b46174c0b69b7e9"
libc = "musl"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "ca39a474f346becfe56a2d999b1a44519c651da1d880cd36e5a4aebe2ba52c2f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.aarch64-linux-musl.tar.gz"
[[GAP_pkg_anupq]]
arch = "aarch64"
git-tree-sha1 = "55e25554ccd1693dafd0b82c80a2b1c7485ab43a"
os = "freebsd"

    [[GAP_pkg_anupq.download]]
    sha256 = "fd303e731a4ba5fe7d4fa870f476fb56f7383500bcb968f1456d1b06d17b2b04"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_anupq]]
arch = "powerpc64le"
git-tree-sha1 = "e527e96ff9e8e94238e5f2f77db09a56b08a1636"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "13fdd002387dda33acf6fd74d0dd5bf5acae9b8ecf209ee1b196936fc371d374"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "8463820adbc7f2f5ff4095384c36cde507a1e9b6"
os = "macos"

    [[GAP_pkg_anupq.download]]
    sha256 = "ee5686dde8faba3e78cb1786176e673c726a4709e608ebc8cb462a076fe23931"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "5d25d4e8491185a43e9373adf931aa2346fccd2d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "a8b7a09ea8488b31068f2cb4c11ccbc77cce86b66bd6d5e3d947e9422fa978b0"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "7a7cf3d28fcb869308af10cd4516b118bf708709"
libc = "musl"
os = "linux"

    [[GAP_pkg_anupq.download]]
    sha256 = "026e298aba47039656bd93cfd78af71ca3e45f771eb2fecfd54957b6384e6b5f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.x86_64-linux-musl.tar.gz"
[[GAP_pkg_anupq]]
arch = "x86_64"
git-tree-sha1 = "8613dfc8084a3fc8a32a456b2f09b2c962c0c744"
os = "freebsd"

    [[GAP_pkg_anupq.download]]
    sha256 = "5723a26d739b8da161834802d9af8a581a3d01364675ff4f8e93dc4a6745cf73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_anupq_jll.jl/releases/download/GAP_pkg_anupq-v300.300.100+0/GAP_pkg_anupq.v300.300.100.x86_64-unknown-freebsd.tar.gz"
